name: CI - Lint and Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    name: Ruff (.py) + mypy (.py + .ipynb)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ruff (only on .py)
        run: ruff check .

      - name: Run mypy with nbqa (supports notebooks)
        run: nbqa mypy . --exclude tests
